name: Daily Auto Commit

on:
  schedule:
    - cron: '15 3 * * *'  # Runs daily at 03:15 UTC
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update Status - 24f1001118@ds.study.iitm.ac.in
        run: |
          echo "Last updated on $(date -u)" > daily_status.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily_status.txt
          git commit -m "Daily update $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
