name: Daily Auto Commit

on:
  schedule:
    - cron: '15 3 * * *'  # Runs daily at 03:15 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Status - 24f1001118@ds.study.iitm.ac.in
        run: |
          echo "Last updated on $(date -u)" > daily_status.txt
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily_status.txt
          git commit -m "Daily update $(date -u '+%Y-%m-%d')" || exit 0
          git push


